import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "./Theme/Providers";
import SideMenu from "./_components/ui/SideMenu/sidemenu";
import Navbar from "./_components/ui/Navbar/navbar";
import { getServerAuthSession } from "~/server/auth";
import { Toaster } from "./_components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/copierlogo.png" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} no-scrollbar`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Providers>
            <NextTopLoader showSpinner={false} height={5} />
            {children}
            <SideMenu />
            <Toaster />
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
